language: php
php:
- 7.3
before_script:
- pecl install -s mongodb
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --dev
script:
- composer pipeline
after_success:
- bash <(curl -s https://codecov.io/bash)