language: php
php:
- 7.3
before_script:
- pecl install -f mongodb
- travis_retry composer install --no-interaction --no-suggest --prefer-source --dev
script:
- composer pipeline
after_success:
- bash <(curl -s https://codecov.io/bash)