version: "3"

services:

  web:
    container_name: fakers_web
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/vhosts.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - data
      - cache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  cache:
    container_name: fakers_cache
    image: redis:5
    ports:
      - "6379:6379"

  data:
    container_name: fakers_data
    image: mongo:4.2
    ports: 
      - "27017:27017"
    
